# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chelloc.proto\x12\x04test\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\nHelloReply\x12\x0e\n\x06result\x18\x01 \x01(\t\"\xaf\x01\n\x10HelloTestRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\t\x12\x32\n\x06number\x18\x04 \x03(\x0b\x32\".test.HelloTestRequest.NumberEntry\x1a>\n\x0bNumberEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1e\n\x05value\x18\x02 \x01(\x0b\x32\x0f.test.ReqNumber:\x02\x38\x01\"9\n\tReqNumber\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x11\n\tis_active\x18\x03 \x01(\x08\"\x10\n\x0eHelloTestReply\"+\n\x1bTestClientRecvStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientRecvStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"+\n\x1bTestClientSendStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\".\n\x1cTestClientSendStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"*\n\x1aTestClientTwoStreamRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"-\n\x1bTestClientTwoStreamResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xa0\x03\n\x06\x42ibili\x12\x30\n\x08SayHello\x12\x12.test.HelloRequest\x1a\x10.test.HelloReply\x12>\n\x0cSayTestHello\x12\x16.test.HelloTestRequest\x1a\x14.test.HelloTestReply(\x01\x12\x61\n\x14TestClientRecvStream\x12!.test.TestClientRecvStreamRequest\x1a\".test.TestClientRecvStreamResponse\"\x00\x30\x01\x12\x61\n\x14TestClientSendStream\x12!.test.TestClientSendStreamRequest\x1a\".test.TestClientSendStreamResponse\"\x00(\x01\x12^\n\x13TestClientTwoStream\x12 .test.TestClientTwoStreamRequest\x1a!.test.TestClientTwoStreamResponse(\x01\x30\x01\x62\x06proto3')



_HELLOREQUEST = DESCRIPTOR.message_types_by_name['HelloRequest']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
_HELLOTESTREQUEST = DESCRIPTOR.message_types_by_name['HelloTestRequest']
_HELLOTESTREQUEST_NUMBERENTRY = _HELLOTESTREQUEST.nested_types_by_name['NumberEntry']
_REQNUMBER = DESCRIPTOR.message_types_by_name['ReqNumber']
_HELLOTESTREPLY = DESCRIPTOR.message_types_by_name['HelloTestReply']
_TESTCLIENTRECVSTREAMREQUEST = DESCRIPTOR.message_types_by_name['TestClientRecvStreamRequest']
_TESTCLIENTRECVSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['TestClientRecvStreamResponse']
_TESTCLIENTSENDSTREAMREQUEST = DESCRIPTOR.message_types_by_name['TestClientSendStreamRequest']
_TESTCLIENTSENDSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['TestClientSendStreamResponse']
_TESTCLIENTTWOSTREAMREQUEST = DESCRIPTOR.message_types_by_name['TestClientTwoStreamRequest']
_TESTCLIENTTWOSTREAMRESPONSE = DESCRIPTOR.message_types_by_name['TestClientTwoStreamResponse']
HelloRequest = _reflection.GeneratedProtocolMessageType('HelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREQUEST,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloRequest)
  })
_sym_db.RegisterMessage(HelloRequest)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

HelloTestRequest = _reflection.GeneratedProtocolMessageType('HelloTestRequest', (_message.Message,), {

  'NumberEntry' : _reflection.GeneratedProtocolMessageType('NumberEntry', (_message.Message,), {
    'DESCRIPTOR' : _HELLOTESTREQUEST_NUMBERENTRY,
    '__module__' : 'helloc_pb2'
    # @@protoc_insertion_point(class_scope:test.HelloTestRequest.NumberEntry)
    })
  ,
  'DESCRIPTOR' : _HELLOTESTREQUEST,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestRequest)
  })
_sym_db.RegisterMessage(HelloTestRequest)
_sym_db.RegisterMessage(HelloTestRequest.NumberEntry)

ReqNumber = _reflection.GeneratedProtocolMessageType('ReqNumber', (_message.Message,), {
  'DESCRIPTOR' : _REQNUMBER,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.ReqNumber)
  })
_sym_db.RegisterMessage(ReqNumber)

HelloTestReply = _reflection.GeneratedProtocolMessageType('HelloTestReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOTESTREPLY,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.HelloTestReply)
  })
_sym_db.RegisterMessage(HelloTestReply)

TestClientRecvStreamRequest = _reflection.GeneratedProtocolMessageType('TestClientRecvStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTRECVSTREAMREQUEST,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientRecvStreamRequest)
  })
_sym_db.RegisterMessage(TestClientRecvStreamRequest)

TestClientRecvStreamResponse = _reflection.GeneratedProtocolMessageType('TestClientRecvStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTRECVSTREAMRESPONSE,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientRecvStreamResponse)
  })
_sym_db.RegisterMessage(TestClientRecvStreamResponse)

TestClientSendStreamRequest = _reflection.GeneratedProtocolMessageType('TestClientSendStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTSENDSTREAMREQUEST,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientSendStreamRequest)
  })
_sym_db.RegisterMessage(TestClientSendStreamRequest)

TestClientSendStreamResponse = _reflection.GeneratedProtocolMessageType('TestClientSendStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTSENDSTREAMRESPONSE,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientSendStreamResponse)
  })
_sym_db.RegisterMessage(TestClientSendStreamResponse)

TestClientTwoStreamRequest = _reflection.GeneratedProtocolMessageType('TestClientTwoStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTTWOSTREAMREQUEST,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientTwoStreamRequest)
  })
_sym_db.RegisterMessage(TestClientTwoStreamRequest)

TestClientTwoStreamResponse = _reflection.GeneratedProtocolMessageType('TestClientTwoStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _TESTCLIENTTWOSTREAMRESPONSE,
  '__module__' : 'helloc_pb2'
  # @@protoc_insertion_point(class_scope:test.TestClientTwoStreamResponse)
  })
_sym_db.RegisterMessage(TestClientTwoStreamResponse)

_BIBILI = DESCRIPTOR.services_by_name['Bibili']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOTESTREQUEST_NUMBERENTRY._options = None
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_options = b'8\001'
  _HELLOREQUEST._serialized_start=22
  _HELLOREQUEST._serialized_end=50
  _HELLOREPLY._serialized_start=52
  _HELLOREPLY._serialized_end=80
  _HELLOTESTREQUEST._serialized_start=83
  _HELLOTESTREQUEST._serialized_end=258
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_start=196
  _HELLOTESTREQUEST_NUMBERENTRY._serialized_end=258
  _REQNUMBER._serialized_start=260
  _REQNUMBER._serialized_end=317
  _HELLOTESTREPLY._serialized_start=319
  _HELLOTESTREPLY._serialized_end=335
  _TESTCLIENTRECVSTREAMREQUEST._serialized_start=337
  _TESTCLIENTRECVSTREAMREQUEST._serialized_end=380
  _TESTCLIENTRECVSTREAMRESPONSE._serialized_start=382
  _TESTCLIENTRECVSTREAMRESPONSE._serialized_end=428
  _TESTCLIENTSENDSTREAMREQUEST._serialized_start=430
  _TESTCLIENTSENDSTREAMREQUEST._serialized_end=473
  _TESTCLIENTSENDSTREAMRESPONSE._serialized_start=475
  _TESTCLIENTSENDSTREAMRESPONSE._serialized_end=521
  _TESTCLIENTTWOSTREAMREQUEST._serialized_start=523
  _TESTCLIENTTWOSTREAMREQUEST._serialized_end=565
  _TESTCLIENTTWOSTREAMRESPONSE._serialized_start=567
  _TESTCLIENTTWOSTREAMRESPONSE._serialized_end=612
  _BIBILI._serialized_start=615
  _BIBILI._serialized_end=1031
# @@protoc_insertion_point(module_scope)
